# Generated by Django 5.0.6 on 2024-05-15 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_social', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Obra_Social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.obrasocial'),
        ),
    ]
