# Generated by Django 5.0.6 on 2024-05-17 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_delete_paciente'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='idSocio',
        ),
        migrations.AddField(
            model_name='paciente',
            name='historiaClinica',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medico_tratante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente_medicos', to='medicos.medicos'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='obraSocial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente_obrasocial', to='pacientes.obrasocial', verbose_name='Socio ID'),
        ),
    ]
