# Generated by Django 5.0.6 on 2024-05-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicos',
            options={'verbose_name': 'Medicos', 'verbose_name_plural': 'Medicos'},
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='especialidad',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
