# Generated by Django 5.0.6 on 2024-05-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
