# Generated by Django 5.0.6 on 2024-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_delete_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='matricula',
            field=models.PositiveIntegerField(unique=True, verbose_name='Matricula Nacional'),
        ),
    ]
